// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udsjbndidfkykfbbdofl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkc2pibmRpZGZreWtmYmJkb2ZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MDYwNjcsImV4cCI6MjA2NzM4MjA2N30.ZrEBkCz6SqmcXU-eHInlcBzxAT6MFL64048F-bdJvO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});